### ISSUE TITLE
How to send multiMssage?I use SubmitMultiExample but it does't work

### ISSUE THREAD

**Issue by SunWukong2018** [opentelecoms-org/jsmpp#114]
String[] desNum = desAddr.split(",");
                if (desNum.length > 1) {
                    Address[] addresses = new Address[desNum.length];
                    for (int i = 0; i < desNum.length; i++) {
                        Address address = new Address(TypeOfNumber.INTERNATIONAL, NumberingPlanIndicator.UNKNOWN, desNum[i]);
                        addresses[i] = address;
                    }
                    SubmitMultiResult submitMultiResult = session.submitMultiple(null, TypeOfNumber.UNKNOWN, NumberingPlanIndicator.UNKNOWN, sourceAddr,
                            addresses, new ESMClass(), (byte) 0, (byte) 0, null, null,
                            new RegisteredDelivery(SMSCDeliveryReceipt.DEFAULT), ReplaceIfPresentFlag.REPLACE,
                            DataCodings.ZERO, (byte) 0,
                            msg.getBytes(ENCODE));
                    messageId = submitMultiResult.getMessageId();
**thow exceptions:**
Exception in thread "pool-2-thread-2" java.lang.ArrayIndexOutOfBoundsException: 16
	at org.jsmpp.util.SequentialBytesReader.readCString(SequentialBytesReader.java:64)
	at org.jsmpp.util.DefaultDecomposer.submitMultiResp(DefaultDecomposer.java:539)
	at org.jsmpp.session.state.SMPPSessionBoundTX.processSubmitMultiResp(SMPPSessionBoundTX.java:77)
	at org.jsmpp.session.PDUProcessTask.run(PDUProcessTask.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pmoerenhout** [comment]
Hi Sun, from the log, I see that during the reading of the messageId of the received submit_multi_resp, scanning for the 0x00 byte, the data stream is exhausted. Do you have the network log of this message? Either some data is not received, or the header is not matching the data length...

**Comment by SunWukong2018** [comment]
org.jsmpp.extra.ResponseTimeoutException: No response after waiting for 5000 millis when executing submit_multi with session 442ba3fa and sequence_number 2
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:297)
	at org.jsmpp.session.SMPPSession.submitMultiple(SMPPSession.java:356)
	at org.jsmpp.examples.StressClient.sendMultiMessage(StressClient.java:202)
	at org.jsmpp.examples.StressClient$1.run(StressClient.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jsmpp.extra.ResponseTimeoutException: No response after 5000 millis
	at org.jsmpp.extra.PendingResponse.waitDone(PendingResponse.java:119)
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:291)
	... 6 more

**Comment by pmoerenhout** [comment]
Hi, this means after the submit_multi_sm was send, and waiting for 5 seconds, there was still no answer received from the SMSC. You could increase the timeout value to see if something is received. Afterwise contact the SMSC operator and check why no answer was generated.

**Comment by SunWukong2018** [comment]
20 seconds still no answer,I use StressServer on my PC as the SMPP sever .and use StressClient as cleint to send SMS.

org.jsmpp.extra.ResponseTimeoutException: No response after waiting for 20000 millis when executing submit_multi with session 3b39ffb8 and sequence_number 2
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:297)
	at org.jsmpp.session.SMPPSession.submitMultiple(SMPPSession.java:356)
	at org.jsmpp.examples.StressClient.sendMultiMessage(StressClient.java:202)
	at org.jsmpp.examples.StressClient$1.run(StressClient.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jsmpp.extra.ResponseTimeoutException: No response after 20000 millis
	at org.jsmpp.extra.PendingResponse.waitDone(PendingResponse.java:119)
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:291)
	... 6 more

**Comment by pmoerenhout** [comment]
Hi, the problem was in DefaultDecomposer, where the PDU body of the submit_multi_resp was not ignored when the status indicated an error. The StressServer currently only supports submit_sm requests. I committed the code with the fix. I will later add handling of the submit_multi in the StressServer.

**Comment by SunWukong2018** [comment]
Hi I pull ourCode and run it ,shows:
org.jsmpp.extra.NegativeResponseException: Negative response 00000008 (System Error) found
	at org.jsmpp.session.AbstractSession.validateResponse(AbstractSession.java:244)
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:305)
	at org.jsmpp.session.SMPPSession.submitMultiple(SMPPSession.java:362)
	at org.jsmpp.examples.StressClient.sendMultiMessage(StressClient.java:202)
	at org.jsmpp.examples.StressClient$1.run(StressClient.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pmoerenhout** [comment]
Yes, submit_multi was not implemented. I updated StressServer now to send the submit_multi_resp. See org.jsmpp.examples.StressServer#onAcceptSubmitMulti

**Comment by SunWukong2018** [comment]
ok bug fixed，thanks a lot

**Comment by SunWukong2018** [comment]
I run it on ISP server and use StressClient as SMS client：

2020-02-24 04:05:36,309 [pool-2-thread-2] ERROR org.jsmpp.session.state.AbstractGenericSMPPSessionBound - Receive generick_nack. command_status=00000003, sequence_number=00000002
2020-02-24 04:05:36,309 [pool-1-thread-1] ERROR org.jsmpp.examples.StressClient - Failed submit short message 'hello jsmpp' to 918377039341,919820018674
org.jsmpp.GenericNackResponseException: Receive generic_nack with command_status 00000003
	at org.jsmpp.session.state.AbstractGenericSMPPSessionBound.processGenericNack(AbstractGenericSMPPSessionBound.java:97)
	at org.jsmpp.session.PDUProcessTask.run(PDUProcessTask.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pmoerenhout** [comment]
I released 2.3.9 to Maven including the fix.
