### ISSUE TITLE
Password length bug?

### ISSUE THREAD

**Issue by PascalSchumacher** [opentelecoms-org/jsmpp#67]
If I try to use a nine character password I get:

```
org.jsmpp.PDUStringException: C-Octet String value '123456789' length must be less than 9. Actual length is 9
              at org.jsmpp.util.StringValidator.validateString(StringValidator.java:40) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.util.DefaultComposer.bind(DefaultComposer.java:68) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.DefaultPDUSender.sendBind(DefaultPDUSender.java:96) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.SynchronizedPDUSender.sendBind(SynchronizedPDUSender.java:88) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.session.BindCommandTask.executeTask(BindCommandTask.java:59) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:277) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.session.SMPPSession.sendBind(SMPPSession.java:296) ~[jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.session.SMPPSession.connectAndBind(SMPPSession.java:234) [jsmpp-2.3.4.jar:2.3.4]
              at org.jsmpp.session.SMPPSession.connectAndBind(SMPPSession.java:201) [jsmpp-2.3.4.jar:2.3.4]
              at org.apache.camel.component.smpp.SmppProducer.createSession(SmppProducer.java:95) [camel-smpp-2.19.1.jar:2.19.1]
              at org.apache.camel.component.smpp.SmppProducer.doStart(SmppProducer.java:80) [camel-smpp-2.19.1.jar:2.19.1]
              at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) [camel-core
```

According to "Short Message Peer to Peer Protocol Specification v3.4 - 12-Oct-1999 Issue 1.2", "4.1.1 “BIND_TRANSMITTER” Syntax":

```
Field Name | Size octets | Type
password   | Var. max 9  | COctet String
```

Sorry if I'm missunderstanding the specification, but shouldn't nine character long passwords be allowed?

**Comment by pmoerenhout** [comment]
The C-Octet string is always ending with a NULL (0x00) character. The NULL character still counts as octet, leaving 8 octets for the password itself.

**Comment by PascalSchumacher** [comment]
Thanks for the information and sorry for opening this invalid issue.

**Comment by daraul** [comment]
Is this a limitation of the protocol, or this library? I have used longer passwords with the same SMPP server, but with [python-smpplib](https://github.com/python-smpplib/python-smpplib).

**Comment by ml-markhay** [comment]
> Is this a limitation of the protocol, or this library? I have used longer passwords with the same SMPP server, but with [python-smpplib](https://github.com/python-smpplib/python-smpplib). Maybe the SMPP server I use implements some other version of the spec.

All versions of SMPP have passwords of type C-Octet String with a maximum length of 9 octets including NULL.  When adhering to the SMPP specification [(smpp.org),](https://smpp.org) passwords can therefore not be greater than 8 octets plus NULL. 

Some SMPP servers deviate from the SMPP specification.
