### ISSUE TITLE
NPE in DeliveryReceipt constructor

### ISSUE THREAD

**Issue by assens** [opentelecoms-org/jsmpp#74]
Hi, I'm using Camel SMPP and I'm getting Delivery Receipts from my SMSC which do not have submit date and done date. According to the SMPP v4.3 specs, Appendix B, the format of the Delivery Receipt message is SMSC vendor specific. 

The following exception is thrown when a delivery receipt is received:
```
2017-12-20 12:25:40.903 DEBUG 7 --- [onsumer[SMS.MT]] o.a.c.c.smpp.SmppSubmitSmCommand         : Sending short message 0 for exchange id 'ID-bcf27a5a104f-1513772191424-0-2'...
2017-12-20 12:25:41.015 DEBUG 7 --- [onsumer[SMS.MT]] o.a.c.c.smpp.SmppSubmitSmCommand         : Sent short message for exchange id 'ID-bcf27a5a104f-1513772191424-0-2' and received message ids '[1846655173]'
2017-12-20 12:25:48.374 DEBUG 7 --- [pool-3-thread-1] o.a.c.c.s.MessageReceiverListenerImpl    : Received a deliverSm PDUHeader(94, 00000005, 00000000, 6)
2017-12-20 12:25:48.375  WARN 7 --- [pool-3-thread-1] o.a.camel.component.smpp.SmppConsumer    : Cannot create exchange. This exception will be ignored.. Caused by: [org.jsmpp.util.InvalidDeliveryReceiptException - There is an error found when parsing delivery receipt]

org.jsmpp.util.InvalidDeliveryReceiptException: There is an error found when parsing delivery receipt
	at org.jsmpp.bean.DeliveryReceipt.<init>(DeliveryReceipt.java:78)
	at org.jsmpp.util.DefaultDecomposer.deliveryReceipt(DefaultDecomposer.java:392)
	at org.jsmpp.util.DefaultDecomposer.deliveryReceipt(DefaultDecomposer.java:402)
	at org.jsmpp.bean.DefaultDeliveryReceiptStripper.strip(DefaultDeliveryReceiptStripper.java:36)
	at org.jsmpp.bean.DefaultDeliveryReceiptStripper.strip(DefaultDeliveryReceiptStripper.java:27)
	at org.jsmpp.bean.DeliverSm.getDeliveryReceipt(DeliverSm.java:63)
	at org.jsmpp.bean.DeliverSm.getShortMessageAsDeliveryReceipt(DeliverSm.java:50)
	at org.apache.camel.component.smpp.SmppBinding.createSmppMessage(SmppBinding.java:125)
	at org.apache.camel.component.smpp.SmppEndpoint.createOnAcceptDeliverSmExchange(SmppEndpoint.java:122)
	at org.apache.camel.component.smpp.SmppEndpoint.createOnAcceptDeliverSmExchange(SmppEndpoint.java:106)
	at org.apache.camel.component.smpp.MessageReceiverListenerImpl.onAcceptDeliverSm(MessageReceiverListenerImpl.java:70)
	at org.jsmpp.session.SMPPSession.fireAcceptDeliverSm(SMPPSession.java:461)
	at org.jsmpp.session.SMPPSession.access$300(SMPPSession.java:94)
	at org.jsmpp.session.SMPPSession$ResponseHandlerImpl.processDeliverSm(SMPPSession.java:480)
	at org.jsmpp.session.state.SMPPSessionBoundRX.processDeliverSm0(SMPPSessionBoundRX.java:109)
	at org.jsmpp.session.state.SMPPSessionBoundRX.processDeliverSm(SMPPSessionBoundRX.java:51)
	at org.jsmpp.session.PDUProcessTask.run(PDUProcessTask.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.jsmpp.bean.DeliveryReceipt.string2Date(DeliveryReceipt.java:413)
	at org.jsmpp.bean.DeliveryReceipt.<init>(DeliveryReceipt.java:68)
	... 19 common frames omitted
```

**Comment by pmoerenhout** [comment]
I merged your code changes. For SMSC specific delivery receipts, you can always create your own receipt and handler. I will look into the default handler to be more relaxed on missing items.
