### ISSUE TITLE
About java.io.EOFException

### ISSUE THREAD

**Issue by SeaCN** [opentelecoms-org/jsmpp#84]
This exception happen when I submitShortMessage(),

`2018-04-11 08:22:37.864 [http-nio-8080-exec-4] INFO  org.jsmpp.session.SMPPSession - Connected to /10.12.51.27
2018-04-11 08:22:37.865 [PDUReaderWorker: org.jsmpp.session.SMPPSession@4bc1e38c] INFO  org.jsmpp.session.SMPPSession - Starting PDUReaderWorker
2018-04-11 08:22:38.030 [http-nio-8080-exec-4] INFO  org.jsmpp.bean.OptionalParameters - Optional Parameter Tag class org.jsmpp.bean.OptionalParameter$Sc_interface_version not found
2018-04-11 08:22:38.030 [http-nio-8080-exec-4] INFO  org.jsmpp.session.SMPPSession - Changing processor degree to 3
2018-04-11 08:22:38.030 [http-nio-8080-exec-4] INFO  com.panshi.payproxy.controller.SmppController - Connected with SMSC with system id RockyMobi
2018-04-11 08:22:38.253 [http-nio-8080-exec-4] INFO  com.panshi.payproxy.controller.SmppController - Message submitted, message_id is 5149464B
2018-04-11 08:22:38.461 [PDUReaderWorker: org.jsmpp.session.SMPPSession@4bc1e38c] WARN  org.jsmpp.session.SMPPSession - IOException while reading:
java.io.EOFException: null
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.jsmpp.DefaultPDUReader.readPDUHeader(DefaultPDUReader.java:40)
	at org.jsmpp.session.SMPPSession$PDUReaderWorker.readPDU(SMPPSession.java:598)
	at org.jsmpp.session.SMPPSession$PDUReaderWorker.run(SMPPSession.java:582)
2018-04-11 08:22:38.464 [PDUReaderWorker: org.jsmpp.session.SMPPSession@4bc1e38c] INFO  org.jsmpp.session.SMPPSession - PDUReaderWorker stop`

Do you have any idea about it?
Forgive me the turbid format code, thank you very much!

**Comment by pmoerenhout** [comment]
It looks the remote side drops the connection, after you have submitted the submit_sm and have received the submit_sm_resp. Normally, an SMSC will keep the connection open. If you make a tcpdump and analyze with Wireshark, you can see which side initiates the drop of the TCP connection.
