### ISSUE TITLE
java/org/jsmpp/examples/AsyncSubmitReceiveDeliverSmExample.java

### ISSUE THREAD

**Issue by joce455** [opentelecoms-org/jsmpp#99]
**Hi all, I have the following problem trying the example of AsyncSubmitReceiveDeliverSmExample:**
org.jsmpp.extra.ResponseTimeoutException: No response after waiting for 2000 millis when executing submit_sm with sessionId 808c4177 and sequenceNumber 36
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:295) ~[jsmpp-2.3.7.jar:2.3.7]
	at org.jsmpp.session.SMPPSession.submitShortMessage(SMPPSession.java:328) ~[jsmpp-2.3.7.jar:2.3.7]
	at sms_smpp.sms_smpp.AsyncSubmitReceiveDeliverSmExample$2.run(AsyncSubmitReceiveDeliverSmExample.java:98) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Could someone help me?**

**Comment by pmoerenhout** [comment]
The ResponseTimeoutException occurs, because no response was received within 2 sec after the submit_sm request was send. To what kind of software or SMSC do you connect?
